import { createComponentDispatch } from "./component-host/dispatch.js";
import type {
	LixBinding,
	LixStorageConfig,
	SyncServerBindingOptions,
	TelemetryDispatch,
	TelemetryParentContext,
	OpenProgressDispatch,
	SnapshotRestoreBinding,
} from "./binding-types.js";
import { restoreSnapshot } from "./snapshot-restore.js";
import { initializeWasm } from "./wasm-init.js";

// Generated before TypeScript compilation and emitted beside this module.
// @ts-ignore Generated by build:wasm and absent in source-only checks.
import { openMemory, openMemoryFromSnapshot } from "./wasm/lix_js_sdk.js";

export async function openMemoryWasmBinding(
	telemetry?: TelemetryDispatch,
	telemetryParent?: TelemetryParentContext,
	openProgress?: OpenProgressDispatch,
	snapshot?: ReadableStream<Uint8Array>,
	durability?: import("./types.js").Durability,
	server?: SyncServerBindingOptions,
): Promise<LixBinding> {
	await initializeWasm();
	const componentDispatch = createComponentDispatch();
	if (snapshot) {
		return restoreSnapshot(
			snapshot,
			openMemoryFromSnapshot(
				telemetry,
				telemetryParent,
				openProgress,
				componentDispatch,
				durability,
			) as SnapshotRestoreBinding<LixBinding>,
		);
	}
	return openMemory(
		telemetry,
		telemetryParent,
		server,
		openProgress,
		componentDispatch,
		durability,
	) as Promise<LixBinding>;
}

export async function openNodeWasmBinding(
	storage: LixStorageConfig,
	telemetry?: TelemetryDispatch,
	parent?: TelemetryParentContext,
	server?: SyncServerBindingOptions,
	progress?: OpenProgressDispatch,
	snapshot?: ReadableStream<Uint8Array>,
): Promise<LixBinding> {
	if (storage.kind === "memory")
		return openMemoryWasmBinding(
			telemetry,
			parent,
			progress,
			snapshot,
			storage.durability,
			server,
		);
	if (storage.kind === "filesystem")
		throw new Error("Filesystem storage requires its native runtime");
	return (await import("./binding.browser.js")).openLixBinding(
		storage,
		telemetry,
		parent,
		server,
		progress,
		snapshot,
	);
}
