import type {
	LixStorageConfig,
	LixBinding,
	LixStorageProviderModule,
	SyncServerBindingOptions,
	TelemetryDispatch,
	TelemetryParentContext,
} from "./binding-types.js";
import { initializeBrowserWasm } from "./browser-wasm-init.js";

// Generated before TypeScript compilation and emitted beside this module.
// @ts-ignore Generated by build:wasm and absent in source-only checks.
import initWasm, { openJsStorage, openMemory } from "./wasm/lix_js_sdk.js";

let wasmInitialized: Promise<unknown> | undefined;

function initializeWasm(): Promise<unknown> {
	if (wasmInitialized !== undefined) return wasmInitialized;
	const initialization = initializeBrowserWasm(
		initWasm,
		new URL("./wasm/lix_js_sdk_bg.wasm", import.meta.url),
	);
	wasmInitialized = initialization.catch((error) => {
		wasmInitialized = undefined;
		throw error;
	});
	return wasmInitialized;
}

export async function openLixBinding(
	storage: LixStorageConfig,
	telemetry?: TelemetryDispatch,
	telemetryParent?: TelemetryParentContext,
	server?: SyncServerBindingOptions,
): Promise<LixBinding> {
	await initializeWasm();
	switch (storage.kind) {
		case "memory":
			return openMemory(telemetry, telemetryParent, server) as Promise<LixBinding>;
		case "jsStorage": {
			const module = (await import(
				/* @vite-ignore */ storage.moduleUrl
			)) as unknown as LixStorageProviderModule;
			if (typeof module.createLixStorageProvider !== "function") {
				throw new TypeError(
					`Storage provider module '${storage.moduleUrl}' does not export createLixStorageProvider()`,
				);
			}
			const provider = await module.createLixStorageProvider(storage.options);
			try {
				const binding = (await openJsStorage(
					provider,
					telemetry,
					telemetryParent,
					server,
				)) as unknown as LixBinding;
				return binding;
			} catch (error) {
				await provider.close().catch(() => undefined);
				throw error;
			}
		}
		case "filesystem":
			throw new Error("FilesystemStorage is only available in Node.js");
	}
}
