import { readFile } from "node:fs/promises";
import type {
	LixBinding,
	TelemetryDispatch,
	TelemetryParentContext,
	OpenProgressDispatch,
} from "./binding-types.js";

// Generated before TypeScript compilation and emitted beside this module.
// @ts-ignore Generated by build:wasm and absent in source-only checks.
import initWasm, { openMemory } from "./wasm/lix_js_sdk.js";

let wasmInitialized: Promise<unknown> | undefined;

function initializeWasm(): Promise<unknown> {
	return (wasmInitialized ??= initWasm({
		module_or_path: readFile(
			new URL("./wasm/lix_js_sdk_bg.wasm", import.meta.url),
		),
	}));
}

export async function openMemoryWasmBinding(
	telemetry?: TelemetryDispatch,
	telemetryParent?: TelemetryParentContext,
	openProgress?: OpenProgressDispatch,
): Promise<LixBinding> {
	await initializeWasm();
	return openMemory(
		telemetry,
		telemetryParent,
		undefined,
		openProgress,
	) as Promise<LixBinding>;
}
