import type {
	LixStorageConfig,
	LixBinding,
	TelemetryDispatch,
} from "./binding-types.js";
import { IndexedDbBackend } from "./indexeddb-backend.js";

// Generated before TypeScript compilation and emitted beside this module.
// @ts-expect-error Generated by build:wasm.
import initWasm, { openIndexedDb, openMemory } from "./wasm/lix_js_sdk.js";

let wasmInitialized: Promise<unknown> | undefined;

function initializeWasm(): Promise<unknown> {
	return (wasmInitialized ??= initWasm());
}

export async function openLixBinding(
	storage: LixStorageConfig,
	telemetry?: TelemetryDispatch,
): Promise<LixBinding> {
	await initializeWasm();
	switch (storage.kind) {
		case "memory":
			return openMemory(telemetry) as Promise<LixBinding>;
		case "indexedDb": {
			const backend = await IndexedDbBackend.open(storage.name);
			try {
				return (await openIndexedDb(backend, telemetry)) as LixBinding;
			} catch (error) {
				await backend.close().catch(() => undefined);
				throw error;
			}
		}
		case "filesystem":
			throw new Error("FilesystemStorage is only available in Node.js");
	}
}
