import type {
	LixBackendConfig,
	LixBinding,
	PluginRuntimeDispatch,
} from "./binding-types.js";

// Generated before TypeScript compilation and emitted beside this module.
// @ts-expect-error Generated by build:wasm.
import initWasm, { openMemory } from "./wasm/lix_js_sdk.js";

let wasmInitialized: Promise<unknown> | undefined;

function initializeWasm(): Promise<unknown> {
	return (wasmInitialized ??= initWasm());
}

export async function openLixBinding(
	backend: LixBackendConfig,
	dispatch: PluginRuntimeDispatch,
): Promise<LixBinding> {
	if (backend.kind !== "memory") {
		throw new Error(
			`${backend.kind === "fs" ? "FsBackend" : "SqliteBackend"} is only available in Node.js`,
		);
	}
	await initializeWasm();
	return openMemory(dispatch);
}
