// Generated before TypeScript compilation and emitted beside this module.
// @ts-ignore Generated by build:wasm and absent in source-only checks.
import initWasm from "./wasm/lix_js_sdk.js";
// @ts-ignore Generated by build:wasm from the bytes in the adjacent WASM file.
import wasmSha256 from "./wasm/lix_js_sdk_bg.asset.js";

type LockManager = {
	request<T>(
		name: string,
		options: { mode: "exclusive" },
		callback: () => Promise<T>,
	): Promise<T>;
};

type WasmCache = {
	match(request: string): Promise<Response | undefined>;
	put(request: string, response: Response): Promise<void>;
	delete(request: string | Request): Promise<boolean>;
	keys(): Promise<readonly Request[]>;
};

type WasmCacheStorage = {
	open(name: string): Promise<WasmCache>;
};

type WasmCacheStatus = "hit" | "miss" | "corrupt" | "unavailable";

const WASM_CACHE_NAME = "lix-js-sdk-wasm-v1";
const MAX_CACHED_WASM_RELEASES = 3;

let wasmInitialized: Promise<unknown> | undefined;

/** All local and remote bindings share the same Wasm module in this realm. */
export function initializeWasm(): Promise<unknown> {
	if (!wasmInitialized) {
		const initialization = loadWasm();
		wasmInitialized = initialization;
		// Keep concurrent callers on this attempt, but let a later call retry
		// after a transient fetch or initialization failure.
		void initialization.catch(() => {
			if (wasmInitialized === initialization) wasmInitialized = undefined;
		});
	}
	return wasmInitialized;
}

async function loadWasm(): Promise<unknown> {
	const moduleUrl = new URL("./wasm/lix_js_sdk_bg.wasm", import.meta.url);
	if (typeof process !== "undefined" && process.versions?.node) {
		const { readFile } = await import("node:fs/promises");
		return initWasm({ module_or_path: await readFile(moduleUrl) });
	}

	// The build-generated digest also distinguishes package releases that serve
	// the WASM at a stable URL. CacheStorage keeps large modules available to
	// later workers even when the browser HTTP cache evicts the response.
	const cacheKeyUrl = new URL(moduleUrl);
	cacheKeyUrl.searchParams.set("lix-wasm-sha256", wasmSha256);
	const lockManager = (
		globalThis.navigator as typeof globalThis.navigator & {
			locks?: LockManager;
		}
	)?.locks;
	const run = () => loadBrowserWasm(moduleUrl, cacheKeyUrl);
	if (!lockManager) return run();
	return lockManager.request(
		`lix:browser-wasm:${cacheKeyUrl.href}`,
		{ mode: "exclusive" },
		run,
	);
}

async function loadBrowserWasm(moduleUrl: URL, cacheKeyUrl: URL): Promise<unknown> {
	const cacheAccess = await openWasmCache();
	let cacheStatus: WasmCacheStatus = cacheAccess.cache ? "miss" : "unavailable";
	let cachedResponse: Response | undefined;

	if (cacheAccess.cache) {
		try {
			cachedResponse =
				(await cacheAccess.cache.match(cacheKeyUrl.href)) ?? undefined;
		} catch {
			cacheStatus = "unavailable";
		}
	}

	if (cachedResponse) {
		let module: WebAssembly.Module | undefined;
		try {
			if (!cachedResponse.ok) throw new Error("Cached WASM response is not successful");
			module = await compileWasmResponse(cachedResponse);
		} catch {
			cacheStatus = "corrupt";
			try {
				await cacheAccess.cache?.delete(cacheKeyUrl.href);
			} catch {
				// Removing a bad cache entry is best-effort; online loading can still work.
			}
		}
		if (module) return initWasm({ module_or_path: module });
	}

	let response: Response;
	try {
		response = await fetch(moduleUrl);
	} catch (cause) {
		throw wasmAssetError("wasm_fetch", cacheStatus, cause);
	}
	if (!response.ok) {
		throw wasmAssetError("wasm_fetch", cacheStatus, undefined, response.status);
	}

	let module: WebAssembly.Module;
	try {
		module = await compileWasmResponse(response);
	} catch (cause) {
		throw wasmAssetError("wasm_compile", cacheStatus, cause);
	}

	const initialized = await initWasm({ module_or_path: module });
	if (cacheAccess.cache) {
		try {
			// The response is stored only after successful compilation and init.
			await cacheAccess.cache.put(cacheKeyUrl.href, response.clone());
			await trimWasmCache(cacheAccess.cache, cacheKeyUrl.href);
		} catch {
			// Cache quota and implementation failures must not block online use.
		}
	}
	return initialized;
}

async function openWasmCache(): Promise<{ cache?: WasmCache }> {
	try {
		const cacheStorage = (
			globalThis as typeof globalThis & { caches?: WasmCacheStorage }
		).caches;
		if (!cacheStorage) return {};
		return { cache: await cacheStorage.open(WASM_CACHE_NAME) };
	} catch {
		return {};
	}
}

async function compileWasmResponse(response: Response): Promise<WebAssembly.Module> {
	if (typeof WebAssembly.compileStreaming === "function") {
		try {
			return await WebAssembly.compileStreaming(response.clone());
		} catch (error) {
			// compileStreaming requires application/wasm. Some dev/proxy servers
			// return correct bytes with a generic MIME type; compile those bytes.
			if (!(error instanceof TypeError)) throw error;
		}
	}
	return WebAssembly.compile(await response.clone().arrayBuffer());
}

async function trimWasmCache(cache: WasmCache, currentUrl: string): Promise<void> {
	const keys = await cache.keys();
	const oldKeys = keys.filter((request) => request.url !== currentUrl);
	// Keep the current immutable release plus two recent prior releases so an
	// already-open older tab can still recreate a worker after an app update.
	for (const request of oldKeys.slice(0, Math.max(0, keys.length - MAX_CACHED_WASM_RELEASES))) {
		await cache.delete(request);
	}
}

function wasmAssetError(
	phase: "wasm_fetch" | "wasm_compile",
	cacheStatus: WasmCacheStatus,
	cause?: unknown,
	httpStatus?: number,
): Error & { code: string; details: Record<string, unknown> } {
	const error = new Error(`Unable to load the WebAssembly asset during ${phase}`) as Error & {
		code: string;
		details: Record<string, unknown>;
	};
	error.name = "LixError";
	error.code = "LIX_WASM_ASSET_UNAVAILABLE";
	error.details = {
		phase,
		cacheStatus,
		...(httpStatus === undefined ? {} : { httpStatus }),
	};
	if (cause !== undefined) {
		Object.defineProperty(error, "cause", { value: cause, configurable: true });
	}
	return error;
}
