// Generated before TypeScript compilation and emitted beside this module.
// @ts-ignore Generated by build:wasm and absent in source-only checks.
import initWasm from "./wasm/lix_js_sdk.js";

type LockManager = {
	request<T>(
		name: string,
		options: { mode: "exclusive" },
		callback: () => Promise<T>,
	): Promise<T>;
};

let wasmInitialized: Promise<unknown> | undefined;

/** All local and remote bindings share the same Wasm module in this realm. */
export function initializeWasm(): Promise<unknown> {
	return (wasmInitialized ??= loadWasm());
}

async function loadWasm(): Promise<unknown> {
	const moduleUrl = new URL("./wasm/lix_js_sdk_bg.wasm", import.meta.url);
	if (typeof process !== "undefined" && process.versions?.node) {
		const { readFile } = await import("node:fs/promises");
		return initWasm({ module_or_path: await readFile(moduleUrl) });
	}
	// Chromium can abort a consumer when workers cold-load the same large
	// response concurrently. Hold the cross-realm lock until compilation ends
	// so later workers can consume the completed immutable HTTP cache entry.
	const lockManager = (
		globalThis.navigator as typeof globalThis.navigator & {
			locks?: LockManager;
		}
	)?.locks;
	const run = () => initWasm({ module_or_path: moduleUrl });
	if (!lockManager) return run();
	return lockManager.request(
		`lix:browser-wasm:${moduleUrl.href}`,
		{ mode: "exclusive" },
		run,
	);
}
