import type { LixBinding } from "./binding-types.js";

// Generated before TypeScript compilation and emitted beside this module.
// @ts-expect-error Generated by build:wasm.
import wasmModule from "./wasm/lix_js_sdk_bg.wasm";
// @ts-expect-error Generated by build:wasm.
import { initSync, openMemory } from "./wasm/lix_js_sdk.js";

let initialized = false;

function initializeWasm(): void {
	if (initialized) return;
	initSync({ module: wasmModule });
	initialized = true;
}

/**
 * Opens an in-memory Lix binding directly in a Cloudflare Worker isolate.
 *
 * The browser SDK intentionally uses Web Workers. Workerd does not implement
 * that API, so this entry point initializes the precompiled module directly.
 * Plugin execution is deliberately unavailable in this environment.
 */
export async function openMemoryLix(): Promise<LixBinding> {
	initializeWasm();
	return openMemory(async () => {
		throw new Error("Lix plugin execution is unavailable in Workerd");
	});
}
