import type { LixBinding } from "./binding-types.js";

// Generated before TypeScript compilation and emitted beside this module.
// @ts-expect-error Generated by build:wasm.
import wasmModule from "./wasm/lix_js_sdk_bg.wasm";
// @ts-expect-error Generated by build:wasm.
import { initSync, openMemoryFromSnapshot, parseSqlScript as parseSqlScriptBinding } from "./wasm/lix_js_sdk.js";

export type SqlScriptPlan = {
	statements: SqlScriptStatement[];
};

export type SqlScriptStatement = {
	sql: string;
	paramStart: number;
	paramEnd: number;
};

export interface OpenMemoryLixOptions {
	snapshot?: Uint8Array;
}

export interface WorkerdLixBinding extends LixBinding {
	exportSnapshot(): Promise<Uint8Array>;
}

let initialized = false;

function initializeWasm(): void {
	if (initialized) return;
	initSync({ module: wasmModule });
	initialized = true;
}

/** Parses SQL using the same DataFusion dialect and transaction policy as Lix. */
export function parseSqlScript(
	sql: string,
	providedParamCount: number,
): SqlScriptPlan {
	initializeWasm();
	return parseSqlScriptBinding(sql, providedParamCount) as SqlScriptPlan;
}

/**
 * Opens an in-memory Lix binding directly in a Cloudflare Worker isolate.
 *
 * The browser SDK intentionally uses Web Workers. Workerd does not implement
 * that API, so this entry point initializes the precompiled module directly.
 * Plugin execution is deliberately unavailable in this environment.
 */
export async function openMemoryLix(
	options: OpenMemoryLixOptions = {},
): Promise<WorkerdLixBinding> {
	if (!options || typeof options !== "object" || Array.isArray(options)) {
		throw new TypeError("openMemoryLix() options must be an object");
	}
	if (
		options.snapshot !== undefined &&
		!(options.snapshot instanceof Uint8Array)
	) {
		throw new TypeError("openMemoryLix() snapshot must be a Uint8Array");
	}
	initializeWasm();
	return openMemoryFromSnapshot(
		undefined,
		options.snapshot,
	);
}
