use crate::backend::{add_column_if_missing, execute_ddl_batch};
use crate::common::{storage_scope_key_for_file_id, STORAGE_SCOPE_KEY_COLUMN};
use crate::{LixBackend, LixError, SqlDialect};

const CANONICAL_INDEX_STATEMENTS: &[&str] = &[
    "CREATE INDEX IF NOT EXISTS idx_lix_internal_untracked_change_visibility_change_id \
     ON lix_internal_untracked_change_visibility (change_id)",
    "CREATE UNIQUE INDEX IF NOT EXISTS uq_lix_internal_untracked_change_visibility_append_seq \
     ON lix_internal_untracked_change_visibility (append_seq)",
    "CREATE INDEX IF NOT EXISTS idx_lix_internal_untracked_change_visibility_identity \
     ON lix_internal_untracked_change_visibility (version_id, visibility_kind, entity_id, schema_key, file_id, append_seq)",
    "CREATE INDEX IF NOT EXISTS idx_lix_internal_untracked_change_visibility_schema \
     ON lix_internal_untracked_change_visibility (visibility_kind, version_id, schema_key)",
    "CREATE UNIQUE INDEX IF NOT EXISTS uq_lix_internal_entity_state_timeline_breakpoint_scope_identity \
     ON lix_internal_entity_state_timeline_breakpoint (root_commit_id, entity_id, schema_key, storage_scope_key, from_depth)",
    "CREATE INDEX IF NOT EXISTS idx_lix_internal_entity_state_timeline_breakpoint_root_depth \
     ON lix_internal_entity_state_timeline_breakpoint (root_commit_id, from_depth)",
    "CREATE INDEX IF NOT EXISTS idx_lix_internal_entity_state_timeline_breakpoint_lookup \
     ON lix_internal_entity_state_timeline_breakpoint (root_commit_id, entity_id, storage_scope_key, schema_key, from_depth)",
    "CREATE INDEX IF NOT EXISTS idx_lix_internal_entity_state_timeline_breakpoint_filters \
     ON lix_internal_entity_state_timeline_breakpoint (root_commit_id, file_id, plugin_key, schema_key, entity_id, from_depth)",
    "CREATE INDEX IF NOT EXISTS idx_lix_internal_entity_state_timeline_breakpoint_scope_filters \
     ON lix_internal_entity_state_timeline_breakpoint (root_commit_id, storage_scope_key, plugin_key, schema_key, entity_id, from_depth)",
];

pub(crate) async fn init(backend: &dyn LixBackend) -> Result<(), LixError> {
    let create_table_statements = canonical_create_table_statements(backend.dialect());
    let create_table_statement_refs = create_table_statements
        .iter()
        .map(String::as_str)
        .collect::<Vec<_>>();
    execute_ddl_batch(backend, "canonical.tables", &create_table_statement_refs).await?;
    ensure_breakpoint_storage_scope_keys(backend).await?;
    execute_ddl_batch(backend, "canonical.indexes", CANONICAL_INDEX_STATEMENTS).await
}

fn canonical_create_table_statements(dialect: SqlDialect) -> Vec<String> {
    let mut statements = vec![
        "CREATE TABLE IF NOT EXISTS lix_internal_snapshot (\
         id TEXT PRIMARY KEY,\
         content TEXT\
         )"
        .to_string(),
        "INSERT INTO lix_internal_snapshot (id, content) \
         SELECT 'no-content', NULL \
         WHERE NOT EXISTS ( \
           SELECT 1 FROM lix_internal_snapshot WHERE id = 'no-content' \
         )"
        .to_string(),
        "CREATE TABLE IF NOT EXISTS lix_internal_change (\
         id TEXT PRIMARY KEY,\
         entity_id TEXT NOT NULL,\
         schema_key TEXT NOT NULL,\
         schema_version TEXT NOT NULL,\
         file_id TEXT,\
         plugin_key TEXT,\
         snapshot_id TEXT NOT NULL,\
         metadata TEXT,\
         created_at TEXT NOT NULL\
         )"
        .to_string(),
    ];

    match dialect {
        SqlDialect::Sqlite => {
            statements.push(
                "CREATE TABLE IF NOT EXISTS lix_internal_untracked_change_visibility (\
                 id TEXT PRIMARY KEY,\
                 change_id TEXT NOT NULL,\
                 version_id TEXT NOT NULL,\
                 visibility_kind TEXT NOT NULL,\
                 entity_id TEXT NOT NULL,\
                 schema_key TEXT NOT NULL,\
                 file_id TEXT,\
                 created_at TEXT NOT NULL,\
                 append_seq INTEGER\
                 )"
                .to_string(),
            );
            statements.push(
                r#"CREATE TRIGGER IF NOT EXISTS trg_lix_internal_untracked_change_visibility_append_seq
AFTER INSERT ON lix_internal_untracked_change_visibility
FOR EACH ROW
WHEN NEW.append_seq IS NULL
BEGIN
  UPDATE lix_internal_untracked_change_visibility
  SET append_seq = NEW.rowid
  WHERE id = NEW.id;
END"#
                    .to_string(),
            );
        }
        SqlDialect::Postgres => {
            statements.push(
                "CREATE TABLE IF NOT EXISTS lix_internal_untracked_change_visibility (\
                 id TEXT PRIMARY KEY,\
                 change_id TEXT NOT NULL,\
                 version_id TEXT NOT NULL,\
                 visibility_kind TEXT NOT NULL,\
                 entity_id TEXT NOT NULL,\
                 schema_key TEXT NOT NULL,\
                 file_id TEXT,\
                 created_at TEXT NOT NULL,\
                 append_seq BIGINT GENERATED BY DEFAULT AS IDENTITY\
                 )"
                .to_string(),
            );
        }
    }

    statements.extend([
        "CREATE TABLE IF NOT EXISTS lix_internal_commit_graph_node (\
         commit_id TEXT PRIMARY KEY,\
         generation BIGINT NOT NULL\
         )"
        .to_string(),
        "CREATE INDEX IF NOT EXISTS idx_lix_internal_commit_graph_node_generation \
         ON lix_internal_commit_graph_node (generation)"
            .to_string(),
        "CREATE TABLE IF NOT EXISTS lix_internal_entity_state_timeline_breakpoint (\
         root_commit_id TEXT NOT NULL,\
         entity_id TEXT NOT NULL,\
         schema_key TEXT NOT NULL,\
         file_id TEXT,\
         storage_scope_key TEXT NOT NULL,\
         from_depth BIGINT NOT NULL,\
         plugin_key TEXT,\
         schema_version TEXT NOT NULL,\
         metadata TEXT,\
         snapshot_id TEXT NOT NULL,\
         change_id TEXT NOT NULL,\
         PRIMARY KEY (root_commit_id, entity_id, schema_key, storage_scope_key, from_depth)\
         )"
        .to_string(),
        "CREATE TABLE IF NOT EXISTS lix_internal_timeline_status (\
         root_commit_id TEXT PRIMARY KEY,\
         built_max_depth BIGINT NOT NULL,\
         built_at TEXT NOT NULL\
         )"
        .to_string(),
    ]);

    statements
}

async fn ensure_breakpoint_storage_scope_keys(backend: &dyn LixBackend) -> Result<(), LixError> {
    add_column_if_missing(
        backend,
        "lix_internal_entity_state_timeline_breakpoint",
        STORAGE_SCOPE_KEY_COLUMN,
        &format!(
            "TEXT NOT NULL DEFAULT '{}'",
            storage_scope_key_for_file_id(None)
        ),
    )
    .await?;
    backend
        .execute(
            &format!(
                "UPDATE lix_internal_entity_state_timeline_breakpoint \
                 SET {storage_scope_key} = CASE \
                   WHEN file_id IS NULL THEN '{engine_scope}' \
                   ELSE 'file:' || file_id \
                 END",
                storage_scope_key = STORAGE_SCOPE_KEY_COLUMN,
                engine_scope = storage_scope_key_for_file_id(None),
            ),
            &[],
        )
        .await?;
    Ok(())
}
