import { HttpTransportError, type HttpTransport } from "../http-transport.js";
import { initializeWasm } from "../wasm-init.js";
import { emitOpenProgress } from "../open-progress.js";
import type { LixOpenProgress, LixOpenReport } from "../types.js";

export const ADMISSION_PROTOCOL_EPOCH = 22;
export const ADMISSION_STORAGE_EPOCH = 82;
export type AdmissionIdentity = {
  repositoryId: string;
  principalId: string;
  protocolEpoch: number;
  storageEpoch: number;
};
const ANONYMOUS_ACCOUNT_ID = "00000000-0000-7000-8000-000000000002";

export function sharedCredentialKey(url: string, headers: [string, string][]): string {
  const entries: [string, string][] = [];
  // Replica routing is not an authentication credential. Preserve pre-routing offline proofs.
  new Headers(headers).forEach((value, key) => {
    if (key !== "lix-replica-id") entries.push([key, value]);
  });
  return JSON.stringify([url, entries]);
}
export function sameAdmission(a: AdmissionIdentity, b: AdmissionIdentity): boolean {
  return a.repositoryId === b.repositoryId && a.principalId === b.principalId &&
    a.protocolEpoch === b.protocolEpoch && a.storageEpoch === b.storageEpoch;
}

/** Rust owns read-only admission, upgrade waiting, and progress. */
export async function requestAdmission(url: string, credentials: [string, string][], transport: HttpTransport,
  options: { onProgress?: (event: LixOpenProgress) => void; onReport?: (report: LixOpenReport) => void } = {},
): Promise<AdmissionIdentity> {
  await initializeWasm();
  // @ts-ignore Generated by build:wasm and absent in source-only checks.
  const { admitRemote } = await import("../wasm/lix_js_sdk.js");
  const admissionTransport: HttpTransport = request => transport({
    ...request,
    init: { ...request.init,
      signal: request.init.signal
        ? AbortSignal.any([request.init.signal, AbortSignal.timeout(10_000)])
        : AbortSignal.timeout(10_000),
      cache: "no-store", redirect: "error", credentials: "omit",
    },
  });
  const result = await admitRemote(url, admissionTransport, credentials,
    options.onProgress ? (event: LixOpenProgress) => emitOpenProgress(options.onProgress, event) : undefined,
  ) as { identity: AdmissionIdentity; report: LixOpenReport };
  options.onReport?.(result.report);
  return result.identity;
}

/** Memory-only proofs grant cached local attachment, never remote authorization. */
export class SharedAdmissionCache {
  private readonly revocations = new Map<string, number>();
  private readonly proofs = new Map<string, AdmissionIdentity>();
  record(url: string, headers: [string, string][], identity: AdmissionIdentity): void {
    // Invisible cookies/custom-fetch identity cannot be a credential proof.
    if (!new Headers(headers).get("authorization") && identity.principalId !== ANONYMOUS_ACCOUNT_ID) return;
    if (this.proofs.size >= 64) this.proofs.delete(this.proofs.keys().next().value!);
    this.proofs.set(sharedCredentialKey(url, headers), { ...identity });
  }
  generation(url: string, headers: [string, string][]): number {
    return this.revocations.get(sharedCredentialKey(url, headers)) ?? 0;
  }
  remove(url: string, headers: [string, string][]): void {
    const key = sharedCredentialKey(url, headers);
    this.revocations.set(key, this.generation(url, headers) + 1);
    this.proofs.delete(key);
  }
  async persistLocal(url: string, headers: [string, string][], generation: number,
    write: () => Promise<void>, remove: () => Promise<void>): Promise<void> {
    if (this.generation(url, headers) !== generation) return;
    await write();
    if (this.generation(url, headers) !== generation) await remove();
  }
  async verify(url: string, headers: [string, string][], expected: AdmissionIdentity | undefined,
    probe: () => Promise<AdmissionIdentity>, allowOffline = true): Promise<{ identity: AdmissionIdentity; online: boolean }> {
    const generation = this.generation(url, headers);
    let identity: AdmissionIdentity;
    let online = true;
    try { identity = await probe(); }
    catch (error) {
      if (!(error instanceof Error) || (error as {code?: string}).code !== "LIX_TRANSPORT_NETWORK") throw error;
      const known = this.proofs.get(sharedCredentialKey(url, headers));
      if (!allowOffline || !known || !expected || !sameAdmission(known, expected)) {
        throw new HttpTransportError("LIX_IDENTITY_UNVERIFIED_OFFLINE", "Repository identity cannot be verified while offline", { cause: error });
      }
      identity = known;
      online = false;
    }
    if (this.generation(url, headers) !== generation) {
      throw new HttpTransportError("LIX_ADMISSION_AUTH_REJECTED", "Credentials were rejected while admission was in flight");
    }
    if (expected && !sameAdmission(identity, expected)) {
      throw new HttpTransportError("LIX_SHARED_ENGINE_IDENTITY_MISMATCH", "Shared engine repository/account does not match this client");
    }
    if (online) this.record(url, headers, identity);
    return { identity, online };
  }
}
