import type { LixBinding, SnapshotExportBinding } from "../binding-types.js";
import { initializeBrowserWasm } from "../browser-wasm-init.js";
import type { RemoteLixServerOptions } from "../types.js";

// Generated before TypeScript compilation and emitted beside the JS SDK.
// @ts-ignore Generated by build:wasm and absent in source-only checks.
import initWasm, { openRemote } from "../wasm/lix_js_sdk.js";

type RemoteLixClientOptions = {
	initialActiveBranchId?: string;
};

let wasmInitialized: Promise<unknown> | undefined;

function initializeWasm(): Promise<unknown> {
	if (wasmInitialized !== undefined) return wasmInitialized;
	let initialization: Promise<unknown>;
	if (typeof process !== "undefined" && process.versions?.node) {
		initialization = import("node:fs/promises").then(
			({ readFile }) =>
				initWasm({
					module_or_path: readFile(
						new URL("../wasm/lix_js_sdk_bg.wasm", import.meta.url),
					),
				}),
			(error) => {
				wasmInitialized = undefined;
				throw error;
			},
		);
	} else {
		initialization = initializeBrowserWasm(
			initWasm,
			new URL("../wasm/lix_js_sdk_bg.wasm", import.meta.url),
		);
	}
	wasmInitialized = initialization;
	return wasmInitialized;
}

export async function openRemoteLixBinding(
	options: RemoteLixServerOptions,
	clientOptions: RemoteLixClientOptions = {},
): Promise<LixBinding> {
	if (!options || typeof options !== "object") {
		throw new TypeError("openLix() remote server must be an object");
	}
	if (options.mode !== "remote") {
		throw new TypeError("openLix() remote server mode must be 'remote'");
	}
	const remoteFetch = options.fetch ?? globalThis.fetch?.bind(globalThis);
	if (typeof remoteFetch !== "function") {
		throw new TypeError("openLix() remote mode requires fetch");
	}
	if (
		options.headers !== undefined &&
		typeof options.headers !== "function" &&
		!isHeadersInit(options.headers)
	) {
		throw new TypeError(
			"openLix() remote server headers must be HeadersInit or a function",
		);
	}
	if (
		clientOptions.initialActiveBranchId !== undefined &&
		clientOptions.initialActiveBranchId.length === 0
	) {
		throw new TypeError("initialActiveBranchId must be a non-empty string");
	}
	const locator = connectionUrl(options.url);
	const protocolLocator = locator.toString();
	await initializeWasm();
	const binding = (await openRemote(
		protocolLocator,
		remoteFetch,
		options.headers,
		clientOptions.initialActiveBranchId,
	)) as LixBinding;
	binding.exportSnapshot = () =>
		remoteSnapshotExport({
			url: snapshotUrl(locator),
			fetch: remoteFetch,
			headers: options.headers,
		});
	return binding;
}

function remoteSnapshotExport({
	url,
	fetch,
	headers: headerSource,
}: {
	readonly url: URL;
	readonly fetch: typeof globalThis.fetch;
	readonly headers: RemoteLixServerOptions["headers"];
}): SnapshotExportBinding {
	const controller = new AbortController();
	let canceled = false;
	let readerPromise: Promise<ReadableStreamDefaultReader<Uint8Array>> | undefined;
	const reader = () =>
		(readerPromise ??= (async () => {
			const resolvedHeaders =
				typeof headerSource === "function" ? await headerSource() : headerSource;
			const headers = new Headers(resolvedHeaders);
			headers.delete("lix-session-id");
			headers.delete("content-encoding");
			headers.set("accept", "application/vnd.lix.snapshot");
			const response = await fetch(url, {
				headers,
				signal: controller.signal,
			});
			if (!response.ok) throw await remoteSnapshotHttpError(response);
			if (response.body === null) {
				throw remoteSnapshotError(
					"LIX_REMOTE_REQUEST_FAILED",
					"Remote snapshot response did not contain a body",
					{ httpStatus: response.status },
				);
			}
			return response.body.getReader();
		})());
	return {
		next: async () => {
			if (canceled) return undefined;
			const result = await (await reader()).read();
			return result.done ? undefined : result.value;
		},
		cancel: async () => {
			if (canceled) return;
			canceled = true;
			controller.abort();
			const activeReader = await readerPromise?.catch(() => undefined);
			await activeReader?.cancel().catch(() => undefined);
		},
	};
}

function snapshotUrl(locator: URL): URL {
	const url = new URL(locator);
	const lixId = url.pathname.slice("/lix/".length);
	url.pathname = `/lix/v1/${lixId}/snapshot`;
	return url;
}

async function remoteSnapshotHttpError(response: Response): Promise<Error> {
	let body: {
		error?: {
			code?: string;
			message?: string;
			hint?: string;
			details?: unknown;
		};
	} = {};
	try {
		body = (await response.json()) as typeof body;
	} catch {
		// A non-JSON proxy response still becomes a structured remote error.
	}
	const error = remoteSnapshotError(
		body.error?.code ?? "LIX_REMOTE_REQUEST_FAILED",
		body.error?.message ?? `Remote Lix request failed with status ${response.status}`,
		{ httpStatus: response.status, remote: body.error?.details },
	);
	if (body.error?.hint !== undefined) error.hint = body.error.hint;
	return error;
}

function remoteSnapshotError(
	code: string,
	message: string,
	details: unknown,
): Error & { code: string; details: unknown; hint?: string } {
	const error = new Error(message) as Error & {
		code: string;
		details: unknown;
		hint?: string;
	};
	error.name = "LixError";
	error.code = code;
	error.details = details;
	return error;
}

function connectionUrl(value: string | URL): URL {
	let locator: URL;
	try {
		locator = new URL(value);
	} catch {
		throw new TypeError("openLix() remote server url must be an absolute URL");
	}
	if (
		locator.protocol !== "https:" &&
		!(locator.protocol === "http:" && isLoopbackHost(locator.hostname))
	) {
		throw new TypeError(
			"openLix() remote server url must use https (http is allowed only for loopback development)",
		);
	}
	if (locator.search || locator.hash) {
		throw new TypeError(
			"openLix() remote server url must not contain a query or fragment",
		);
	}
	if (locator.username || locator.password) {
		throw new TypeError(
			"openLix() remote server url must not contain credentials",
		);
	}
	if (
		!/^\/lix\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(
			locator.pathname,
		)
	) {
		throw new TypeError(
			"openLix() remote server url path must be exactly /lix/{uuid}",
		);
	}
	return locator;
}

function isLoopbackHost(hostname: string): boolean {
	return (
		hostname === "localhost" ||
		hostname === "[::1]" ||
		/^127(?:\.[0-9]{1,3}){3}$/.test(hostname)
	);
}

function isHeadersInit(value: unknown): value is HeadersInit {
	try {
		new Headers(value as HeadersInit);
		return true;
	} catch {
		return false;
	}
}
