import type { LixBinding } from "../binding-types.js";
import { initializeBrowserWasm } from "../browser-wasm-init.js";
import type { RemoteLixServerOptions } from "../types.js";
import { SERVER_PROTOCOL_PATH } from "./server-protocol.js";

// Generated before TypeScript compilation and emitted beside the JS SDK.
// @ts-ignore Generated by build:wasm and absent in source-only checks.
import initWasm, { openRemote } from "../wasm/lix_js_sdk.js";

type RemoteLixClientOptions = {
	initialActiveBranchId?: string;
};

let wasmInitialized: Promise<unknown> | undefined;

function initializeWasm(): Promise<unknown> {
	if (wasmInitialized !== undefined) return wasmInitialized;
	let initialization: Promise<unknown>;
	if (typeof process !== "undefined" && process.versions?.node) {
		initialization = import("node:fs/promises").then(
			({ readFile }) =>
				initWasm({
					module_or_path: readFile(
						new URL("../wasm/lix_js_sdk_bg.wasm", import.meta.url),
					),
				}),
			(error) => {
				wasmInitialized = undefined;
				throw error;
			},
		);
	} else {
		initialization = initializeBrowserWasm(
			initWasm,
			new URL("../wasm/lix_js_sdk_bg.wasm", import.meta.url),
		);
	}
	wasmInitialized = initialization.catch((error) => {
		wasmInitialized = undefined;
		throw error;
	});
	return wasmInitialized;
}

export async function openRemoteLixBinding(
	options: RemoteLixServerOptions,
	clientOptions: RemoteLixClientOptions = {},
): Promise<LixBinding> {
	if (!options || typeof options !== "object") {
		throw new TypeError("openLix() remote server must be an object");
	}
	if (options.mode !== "remote") {
		throw new TypeError("openLix() remote server mode must be 'remote'");
	}
	const remoteFetch = options.fetch ?? globalThis.fetch?.bind(globalThis);
	if (typeof remoteFetch !== "function") {
		throw new TypeError("openLix() remote mode requires fetch");
	}
	if (
		options.headers !== undefined &&
		typeof options.headers !== "function" &&
		!isHeadersInit(options.headers)
	) {
		throw new TypeError(
			"openLix() remote server headers must be HeadersInit or a function",
		);
	}
	if (
		clientOptions.initialActiveBranchId !== undefined &&
		clientOptions.initialActiveBranchId.length === 0
	) {
		throw new TypeError("initialActiveBranchId must be a non-empty string");
	}
	await initializeWasm();
	return openRemote(
		protocolBaseUrl(options.url).toString(),
		remoteFetch,
		options.headers,
		clientOptions.initialActiveBranchId,
	) as Promise<LixBinding>;
}

function protocolBaseUrl(value: string | URL): URL {
	let repositoryUrl: URL;
	try {
		repositoryUrl = new URL(value);
	} catch {
		throw new TypeError("openLix() remote server url must be an absolute URL");
	}
	if (
		repositoryUrl.protocol !== "http:" &&
		repositoryUrl.protocol !== "https:"
	) {
		throw new TypeError("openLix() remote server url must use http or https");
	}
	if (repositoryUrl.search || repositoryUrl.hash) {
		throw new TypeError(
			"openLix() remote server url must not contain a query or fragment",
		);
	}
	repositoryUrl.pathname = `${repositoryUrl.pathname.replace(/\/$/, "")}${SERVER_PROTOCOL_PATH}`;
	return repositoryUrl;
}

function isHeadersInit(value: unknown): value is HeadersInit {
	try {
		new Headers(value as HeadersInit);
		return true;
	} catch {
		return false;
	}
}
