import type { LixBinding } from "../binding-types.js";
import { initializeWasm } from "../wasm-init.js";
import type { RemoteLixServerOptions } from "../types.js";

// Generated before TypeScript compilation and emitted beside the JS SDK.
// @ts-ignore Generated by build:wasm and absent in source-only checks.
import { openRemote } from "../wasm/lix_js_sdk.js";

type RemoteLixClientOptions = {
	initialActiveBranchId?: string;
};

export async function openRemoteLixBinding(
	options: RemoteLixServerOptions,
	clientOptions: RemoteLixClientOptions = {},
): Promise<LixBinding> {
	if (!options || typeof options !== "object") {
		throw new TypeError("openLix() remote server must be an object");
	}
	if (options.mode !== "remote") {
		throw new TypeError("openLix() remote server mode must be 'remote'");
	}
	const remoteFetch = options.fetch ?? globalThis.fetch?.bind(globalThis);
	if (typeof remoteFetch !== "function") {
		throw new TypeError("openLix() remote mode requires fetch");
	}
	if (
		options.headers !== undefined &&
		typeof options.headers !== "function" &&
		!isHeadersInit(options.headers)
	) {
		throw new TypeError(
			"openLix() remote server headers must be HeadersInit or a function",
		);
	}
	if (
		clientOptions.initialActiveBranchId !== undefined &&
		clientOptions.initialActiveBranchId.length === 0
	) {
		throw new TypeError("initialActiveBranchId must be a non-empty string");
	}
	const locator = connectionUrl(options.url);
	const protocolLocator = locator.toString();
	await initializeWasm();
	return await openRemote(
		protocolLocator,
		remoteFetch,
		options.headers,
		clientOptions.initialActiveBranchId,
	);
}
function connectionUrl(value: string | URL): URL {
	let locator: URL;
	try {
		locator = new URL(value);
	} catch {
		throw new TypeError("openLix() remote server url must be an absolute URL");
	}
	if (
		locator.protocol !== "https:" &&
		!(locator.protocol === "http:" && isLoopbackHost(locator.hostname))
	) {
		throw new TypeError(
			"openLix() remote server url must use https (http is allowed only for loopback development)",
		);
	}
	if (locator.search || locator.hash) {
		throw new TypeError(
			"openLix() remote server url must not contain a query or fragment",
		);
	}
	if (locator.username || locator.password) {
		throw new TypeError(
			"openLix() remote server url must not contain credentials",
		);
	}
	if (
		!/^\/lix\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(
			locator.pathname,
		)
	) {
		throw new TypeError(
			"openLix() remote server url path must be exactly /lix/{uuid}",
		);
	}
	return locator;
}

function isLoopbackHost(hostname: string): boolean {
	return (
		hostname === "localhost" ||
		hostname === "[::1]" ||
		/^127(?:\.[0-9]{1,3}){3}$/.test(hostname)
	);
}

function isHeadersInit(value: unknown): value is HeadersInit {
	try {
		new Headers(value as HeadersInit);
		return true;
	} catch {
		return false;
	}
}
