target-applies-to-host = false

[alias]
# requires: cargo install cargo-bash
b = "bash export LIX_OLDPWD=$PWD && while ! [ -d \"$PWD/packages\" -a -d \"$PWD/plugins\" ]; do cd .. && [[ \"$PWD\" != \"/\" ]] || { echo \"not in lix repo\" && exit 1; }; done;"
lcheck-stable = "b lix_root=$PWD && rust_version=$(python3 -c 'import tomllib; print(tomllib.load(open(\"Cargo.toml\",\"rb\"))[\"workspace\"][\"package\"][\"rust-version\"])') && tmpdir=$(mktemp -d) && trap 'rm -rf \"$tmpdir\"' EXIT && rustup run --install \"$rust_version\" cargo init --bin --vcs none --name lcheck-stable --quiet \"$tmpdir\" && cd \"$tmpdir\" && rustup run --install \"$rust_version\" cargo add --quiet lix_sdk --path \"$lix_root/packages/rs-sdk\" && rustup run --install \"$rust_version\" cargo build"
lclippy = "b NPROC=$(nproc 2>/dev/null || getconf _NPROCESSORS_ONLN 2>/dev/null || sysctl -n hw.physicalcpu 2>/dev/null || echo 1); \"$CARGO\" metadata --format-version 1 --no-deps | jq -r '.packages[].manifest_path' | xargs \"-P$NPROC\" -n1 \"$CARGO\" clippy --all-features --all-targets --manifest-path && exit 0"

[host]
rustflags = [
	# https://blog.rust-lang.org/2023/11/09/parallel-rustc.html
	"-Zthreads=8",
]
# keep host and generic-target rustflags in sync
[target.'cfg(all())']
rustflags = [
	# https://blog.rust-lang.org/2023/11/09/parallel-rustc.html
	"-Zthreads=8",
]

[target.wasm32-unknown-unknown]
rustflags = [
	"--cfg=getrandom_backend=\"wasm_js\"",
]
runner = "wasm-bindgen-test-runner"

[profile.dev]
debug = "line-tables-only"
[profile.dev.package."*"]
debug = false

[profile.debugging]
inherits = "dev"
debug = true

[profile.test]
inherits = "release"
debug = false
debug-assertions = true

[profile.test.build-override]
inherits = "dev"
debug = false
opt-level = 0
debug-assertions = true
overflow-checks = true

[profile.test.package."*"]
debug = false
debug-assertions = false
overflow-checks = false
[profile.test.package."log"]
debug-assertions = true

[profile.release]
trim-paths = true

[profile.bench]
debug = "line-tables-only"

[unstable]
bindeps = true
host-config = true
target-applies-to-host = true
trim-paths = true
