import { beforeAll } from "vitest";
import { initializeWasm } from "../wasm-init.js";
import type { CoreInstrumenter } from "./index.js";
import { registerComponentInstanceCapTests } from "./index.suite.js";

// Generated by build:wasm and absent in source-only checks.
// @ts-ignore
import { instrumentComponentCore } from "../wasm/lix_js_sdk.js";

beforeAll(async () => {
  await initializeWasm();
});

// Exercise the complete Component compilation and instance caps using Rust.
registerComponentInstanceCapTests(
  instrumentComponentCore as CoreInstrumenter,
);
