import { beforeAll } from "vitest";
import { initializeWasm } from "../wasm-init.js";
import type { CoreInstrumenter } from "./index.js";
import { registerCoreInstrumentationTests } from "./instrument.suite.js";

// Generated by build:wasm and absent in source-only checks.
// @ts-ignore
import { instrumentComponentCore } from "../wasm/lix_js_sdk.js";

beforeAll(async () => {
  await initializeWasm();
});

// No Binaryen fallback: this suite exercises the Rust export in Chromium.
registerCoreInstrumentationTests(
  instrumentComponentCore as CoreInstrumenter,
);
