import type { LixBinding } from "../src/binding-types.js";
// Generated by build:wasm. Source-only checks cannot validate the generated API.
// @ts-ignore Generated declaration is absent before build:wasm.
import type { WasmLix, WasmRemoteLix } from "../src/wasm/lix_js_sdk.js";

// Typecheck the actual generated exports, including recursively returned child
// sessions. Assertions in the loader would otherwise hide missing methods.
export function checkGeneratedBindingContract(
	local: WasmLix,
	remote: WasmRemoteLix,
): [LixBinding, LixBinding] {
	return [local, remote];
}
