#!/usr/bin/env node
import { spawn } from "node:child_process";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";
import { embedWasm } from "./wasm-utils.js";

const require = createRequire(import.meta.url);
const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, "..", "..", "..");
const jsSdkDir = join(repoRoot, "packages", "js-sdk");
const targetDir = join(repoRoot, "target", "wasm32-unknown-unknown", "debug");
const engineWasmPath = join(targetDir, "lix_engine_wasm_bindgen.wasm");
const engineOutDir = join(jsSdkDir, "src", "engine-wasm", "wasm");

const sqliteWasmRelativePath = "sqlite-wasm/jswasm/sqlite3.wasm";
const sqliteTargetFile = join(
  jsSdkDir,
  "src",
  "backend",
  "wasm-sqlite.wasm.ts",
);

function run(cmd, args, opts = {}) {
  return new Promise((resolve, reject) => {
    const child = spawn(cmd, args, { stdio: "inherit", ...opts });
    child.on("error", reject);
    child.on("exit", (code) => {
      if (code === 0) resolve();
      else reject(new Error(`${cmd} exited with code ${code ?? 1}`));
    });
  });
}

async function buildEngineWasm() {
  await run("cargo", [
    "build",
    "-p",
    "lix_engine_wasm_bindgen",
    "--target",
    "wasm32-unknown-unknown",
  ]);

  await run("wasm-bindgen", [engineWasmPath, "--target", "web", "--out-dir", engineOutDir]);

  const outRoot = join(jsSdkDir, "src", "engine-wasm");
  const header = `/**\n * @file Auto-generated WebAssembly payload for Lix engine.\n *\n * Generated by scripts/build.js — do not edit manually.\n */\n\n`;
  await embedWasm({
    input: join(engineOutDir, "lix_engine_wasm_bindgen_bg.wasm"),
    outJs: join(outRoot, "engine-wasm-binary.js"),
    outDts: join(outRoot, "engine-wasm-binary.d.ts"),
    header,
  });
}

async function buildSqliteWasm() {
  const pkgPath = require.resolve("@sqlite.org/sqlite-wasm/package.json");
  const packageDir = dirname(pkgPath);
  const sqliteWasmPath = join(packageDir, sqliteWasmRelativePath);

  const header = `/**\n * @file Auto-generated WebAssembly payload for SQLite.\n *\n * Generated by scripts/build.js — do not edit manually.\n */\n\n`;
  await embedWasm({
    input: sqliteWasmPath,
    outJs: sqliteTargetFile,
    outDts: `${sqliteTargetFile}.d.ts`,
    header,
  });
}

async function main() {
  await buildEngineWasm();
  await buildSqliteWasm();
}

main().catch((error) => {
  console.error("[build-wasm] Failed to generate wasm payloads:\n", error);
  process.exit(1);
});
